M48
; DRILL file {KiCad 9.0.0} date 2025-03-19T22:07:39+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-19T22:07:39+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.520
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X4.66Y70.38
T2
X7.25Y30.46
X12.75Y104.2
X145.25Y104.2
X145.25Y29.0
T1
X4.66Y62.98G85X4.66Y62.78
G05
M30
